export const arrayDocumentsOfArchive = [
  {
    idDocument: 1,
    idParent: 1,
    name: 'doc',
    typeOfDocument: '2',
    sizeOfDocument: '2',
    authorsName: 'Силенко П.П',
    dateOfSublication: '2',
    way: '/2',
  },
  {
    idDocument: 2,
    idParent: 1,
    name: 'doc2',
    typeOfDocument: '3',
    sizeOfDocument: '3',
    authorsName: 'Силенко П.П',
    dateOfSublication: '3',
    way: '/2',
  },
  {
    idDocument: 3,
    idParent: 1,
    name: 'doc3',
    typeOfDocument: '4',
    sizeOfDocument: '4',
    authorsName: 'Силенко П.П',
    dateOfSublication: '5',
    way: '/2',
  },
];
