// JSON как объект //
export const date = [
  {
    'id': 341,
    'id_element': 356,
    'nember_register': 1,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 342,
    'id_element': 357,
    'nember_register': 2,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 343,
    'id_element': 358,
    'nember_register': 3,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 344,
    'id_element': 359,
    'nember_register': 4,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 345,
    'id_element': 360,
    'nember_register': 5,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 346,
    'id_element': 361,
    'nember_register': 6,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 347,
    'id_element': 362,
    'nember_register': 7,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 348,
    'id_element': 363,
    'nember_register': 8,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 349,
    'id_element': 364,
    'nember_register': 9,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 350,
    'id_element': 365,
    'nember_register': 10,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы, Доп.соглашение и документы об изменении преамбулы, Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 351,
    'id_element': 366,
    'nember_register': 11,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование, Заявление на опломбирование, Заявление на опломбирование, Заявление на опломбирование',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 352,
    'id_element': 367,
    'nember_register': 12,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 353,
    'id_element': 368,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 354,
    'id_element': 369,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 355,
    'id_element': 370,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 356,
    'id_element': 371,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
  {
    'id': 357,
    'id_element': 372,
    'nember_register': 13,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
  },
];
