// JSON как объект //
export const date = [
  {
    'id': 341,
    'id_element': 3556456,
    'number_register': 1,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
    'date_registration': '01.02.2025',
    'name_sity': 'Ростов-На-Дону',
    'name_street': 'Льва Толстого',
    'number_home': 5,
    'number_body': 5,
    'number_flat': 5,
    'id_documents': [1, 2, 3],
  },
  {
    'id': 342,
    'id_element': 3556456,
    'number_register': 1,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
    'date_registration': '01.02.2025',
    'name_sity': 'Ростов-На-Дону',
    'name_street': 'Льва Толстого',
    'number_home': 5,
    'number_body': 5,
    'number_flat': 5,
    'id_documents': [1, 2, 3],
  },
  {
    'id': 343,
    'id_element': 3556456,
    'number_register': 1,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
    'date_registration': '01.02.2025',
    'name_sity': 'Ростов-На-Дону',
    'name_street': 'Льва Толстого',
    'number_home': 5,
    'number_body': 5,
    'number_flat': 5,
    'id_documents': [1, 2, 3],
  },
];
