// JSON как объект //
export const date = [
  {
    'id': 341,
    'number_register': 4,
    'id_subscriber': 4,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
    'date_registration': '01.02.2025',
    'name_sity': 'Ростов-На-Дону',
    'name_street': 'Льва Толстого',
    'number_home': 5,
    'number_body': 5,
    'number_flat': 5,
    'id_documents': [3, 4],
    'id_parent': 0,
  },
  {
    'id': 342,
    'number_register': 3,
    'id_subscriber': 3,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
    'date_registration': '01.02.2025',
    'name_sity': 'Ростов-На-Дону',
    'name_street': 'Льва Толстого',
    'number_home': 5,
    'number_body': 5,
    'number_flat': 5,
    'id_documents': [2],
    'id_parent': 0,
  },
  {
    'id': 343,
    'number_register': 2,
    'id_subscriber': 2,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
    'date_registration': '01.02.2025',
    'name_sity': 'Ростов-На-Дону',
    'name_street': 'Льва Толстого',
    'number_home': 5,
    'number_body': 5,
    'number_flat': 5,
    'id_documents': [1],
    'id_parent': 1,
  },
  {
    'id': 344,
    'number_register': 1,
    'id_subscriber': 1,
    'type_document': 'Доп.соглашение и документы об изменении преамбулы',
    'comments': 'Заявление на опломбирование ',
    'number__agreement': 12,
    'name_object': 'Силенко И.П',
    'date_registration': '01.02.2025',
    'name_sity': 'Ростов-На-Дону',
    'name_street': 'Льва Толстого',
    'number_home': 5,
    'number_body': 5,
    'number_flat': 5,
    'id_documents': [],
    'id_parent': 2,
  },
];
